module CivsTranslator.ItemToText
open System.Text
open Dotgem.Text

module ColorCodes =
    let getColorFor nodeType textValue =
        match nodeType with
        | NodeType.H1 -> "§f"
        | NodeType.Text ->
            match textValue with
            | TextValue.Text _ -> "§7"
            | TextValue.YesNo x ->
                match x with
                | YesNo.Yes -> "§x§8§a§f§f§8§0"
                | YesNo.No -> "§x§f§f§9§5§8§0"
            | TextValue.Extensive _ -> ""
        | NodeType.ListHeader ->
            match textValue with
            | TextValue.Text _ -> "§x§b§c§c§0§c§c"
            | TextValue.YesNo x ->
                match x with
                | YesNo.Yes -> "§x§8§a§f§f§8§0"
                | YesNo.No -> "§x§f§f§9§5§8§0"
            | TextValue.Extensive _ -> ""
        | NodeType.Point ->
            match textValue with
            | TextValue.Text _ -> "§x§1§7§9§2§9§9"
            | TextValue.YesNo x ->
                match x with
                | YesNo.Yes -> "§x§8§a§f§f§8§0"
                | YesNo.No -> "§x§f§f§9§5§8§0"
            | TextValue.Extensive _ -> ""

let rec coloriseText (sb : StringBuilder) (nodeType) (value : ExtensiveNodeValue) =
    for v in value.Values do
        match v with
        | TextValue.Text t ->
            sb.Append(ColorCodes.getColorFor nodeType v).Append(t) |> ignore
        | TextValue.YesNo x -> sb.Append(ColorCodes.getColorFor nodeType v).Append(YesNo.toGerman(x)) |> ignore
        | TextValue.Extensive x ->
            coloriseText sb nodeType x

let convertNodeLine (sb : StringBuilder) (node : Node) =
    let nodeType = node.NodeType
    let value = node.Value
    sb.AppendSpace(2) |> ignore
    match nodeType with
    | NodeType.H1 ->
        raise(exn "this should not happen")
    | NodeType.Point ->
        sb.Append("§7  §x§7§c§7§f§9§3◉ ") |> ignore
        coloriseText sb nodeType value
        sb.AppendLine() |> ignore
    | NodeType.ListHeader ->
        coloriseText sb nodeType value
        sb.AppendLine() |> ignore
    | NodeType.Text ->
        coloriseText sb nodeType value
        sb.AppendLine() |> ignore

let rec convertNode (sb : StringBuilder) (node : Node) =
    convertNodeLine sb node
    for n in node.Children do
        convertNode sb n

let convertItem (sb : StringBuilder) (item : Item) =
    let key = item.Key
    let name = item.Name
    sb.Append(key).Append("-name: ") |> ignore
    Surround.withQuotes sb ($"§f{name}")
    sb.AppendLine() |> ignore
    sb.Append(key).AppendLine("-desc: |") |> ignore
    for node in item.Description.Children do
        convertNode sb node

let convert (items : Item array) =
    let sb = StringBuilder()
    sb.AppendLine("# Generated by Civs Translator").AppendLine() |> ignore
    for item in items do
        item
        |> convertItem sb
    sb.ToString()

